version: "3.3"
services:
  app:
    build:
      context: .
    container_name: express_app
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      private_network:
        ipv4_address: 172.16.235.10
  db:
    image: mariadb
    container_name: express_db
    volumes:
      - ./storage/mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    networks:
      private_network:
        ipv4_address: 172.16.235.11
  redis:
    image: "redis:alpine"
    container_name: express_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./storage/redis-data:/var/lib/redis
    restart: always
    networks:
      private_network:
        ipv4_address: 172.16.235.12
  adminer:
    image: adminer
    container_name: express_adminer
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: arcs-material
    ports:
      - "8080:8080"
    networks:
      private_network:
        ipv4_address: 172.16.235.13
networks:
  private_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.235.0/24

